/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/destroyedPlanet.glb 
Author: PounUP (https://sketchfab.com/PounUP)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/planet-0104234961624b7aa0cb85d03161babe
Title: Planet
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {Mesh} from "three";
import {useFrame} from "@react-three/fiber";

export function DestroyedPlanet(props) {
  const { nodes, materials } = useGLTF('/models/destroyedPlanet.glb')

  const meshRef = useRef<Mesh>(null!)

    useFrame((_state, delta) => {
        if (meshRef.current) {
            meshRef.current.rotation.z += delta * 0.01;
        }
    });

  return (
    <group {...props} dispose={null}>
      <group ref={meshRef}>
        <mesh
            geometry={nodes.COMBINE_LP_LAM_0.geometry}
            material={materials.material}
            material-emissive="#ff4d01"
            material-emissiveIntensity={4}
            material-toneMapped={false}
        />
        <mesh geometry={nodes.COMBINE_LP_1_0.geometry} material={materials.material_1}/>
        <mesh geometry={nodes.COMBINE_LP_2_0.geometry} material={materials.material_2}/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/destroyedPlanet.glb')
