/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/icePlanet.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function IcePlanet(props) {
  const { nodes, materials } = useGLTF('/models/icePlanet.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.Toy_Planet_4_Toy_Planets_0.geometry} material={materials['Toy_Planets.001']}/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/icePlanet.glb')
