/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ship.glb 
Author: Götz von Berlichingen (https://sketchfab.com/vonBerlichingen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/battlestar-galactica-low-poly-1f5457b4a1514797bb8b5e1e97da1c2d
Title: Battlestar Galactica (low poly)
*/

import { useGLTF } from '@react-three/drei'

export default function Ship(props) {
  const { nodes, materials } = useGLTF('/models/ship.glb')
    return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Material1.geometry} material={materials.texture} />
          <mesh geometry={nodes.Material2.geometry} material={materials.engine} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ship.glb')
