/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/ship.glb --transform 
Files: models/ship.glb [220.8KB] > E:\Programming\Projects\personal-site\public\ship-transformed.glb [46.09KB] (79%)
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {Mesh} from "three";
import {useFrame} from "@react-three/fiber";

export default function Ship(props) {
  const { nodes, materials } = useGLTF('/models/ship-transformed.glb')

    const shipRef = useRef<Mesh>(null!)

    useFrame((state) => {
        const t = state.clock.getElapsedTime();
        shipRef.current.rotation.z = Math.sin(t * 2) * 0.02;
        shipRef.current.position.y = Math.cos(t * 4) * 0.01;
    });

  return (
    <group {...props} dispose={null} ref={shipRef}>
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} position={[0, 0.844, -0.938]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.material_1} position={[-1.5, 0.75, 1.875]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.material_2} position={[-0.313, 0.738, 0.313]} />

        {/*engines*/}
        <mesh geometry={nodes.Object_91.geometry} material={materials.material_3} position={[-1.063, 1, 2.688]} rotation={[Math.PI / 2, Math.PI / 2, 0]}
              // material-emissive="#78cce2"
              // material-emissiveIntensity={2}
              // material-toneMapped={false}
        />
      <mesh geometry={nodes.Object_105.geometry} material={materials.material_4} position={[-0.438, 0.894, 1]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.material_5} position={[0, 0.438, 1.813]} />
    </group>
  )
}

useGLTF.preload('/models/ship-transformed.glb')
