/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/sun.glb --transform 
Files: models/sun.glb [89.92KB] > E:\Programming\Projects\personal-site\public\sun-transformed.glb [30.73KB] (66%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sun(props) {
  const { nodes, materials } = useGLTF('/models/sun-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Toy_Planet_8_Toy_Planets_0.geometry} material={materials.Toy_Planets} position={[0, -0.001, 0.004]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/sun-transformed.glb')
